export const DEFAULTS = {
  wallCabinetHeightMm: 720,
  wallCabinetDepthMm: 300,
  wallCabinetDepthWithBuiltInMicrowaveMm: 330,
  ldspThicknessMm: 16,
  baseTotalHeightMm: 860,
  baseTotalHeightWithGolaMm: 900,
  baseTotalHeightWithGolaAndDishwasherMm: 920,
  baseLegHeightMm: 100,
  countertopThicknessMm: 38,
  baseCabinetDepthMm: 510,
  sinkBaseCabinetDepthMm: 500,
  countertopDepthMm: 600,
  baseRailHeightMm: 100,
  baseShelfCount: 1,
  drawerGuideGapPerSideMm: 13,
  ballBearingDrawerDepthMm: 500,
  ballBearingDrawerGuideLengthMm: 500,
  drawerBottomInsetMm: 3,
  drawerHeightFacadeInsetMm: 54,
  drawerDefaultFacadeHeightMm: 180,
  drawerDefaultCount: 1,
  facadeGapMm: 3,
  ceilingFillerMm: 50,
  stretchCeilingReserveMm: 80,
  ceilingGapMm: 40,
  tallWallCabinetThresholdMm: 850,
  clientTileBacksplashHeightMm: 600,
  ourLdspBacksplashHeightMm: 580,
  gasCooktopHoodDistanceMm: 750,
  autoModuleWidthMm: 600,
  minRemainderForExtraModuleMm: 200,
  shelfCount: 0,
  defaultFacadeMaterial: 'ldsp' as const,
  defaultFacadeThicknessMm: 16 as const,
} as const;
